import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next.JS хичээл",
  description: "Generated by create next app",
  openGraph: {
    title: "Хүүхэд насанд том хүн хүрчээ",
    images:
      "https://giingoo.com/wp-content/uploads/2019/02/huuhed-ugaah-680x350.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="grid grid-cols-3">
        <div className="col-span-1">hehe</div>
        <div className="col-span-2"> {children}</div>
      </div>
    </div>
  );
}
